baseURL: "https://arstarling.ru"
languageCode: en-us
title: arstarling.me
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true

params:
  env: production
  defaultTheme: dark
  author: Arina Skvortsova
  DateFormat: "January 2, 2006"

  profileMode:
    enabled: true
    title: Arina Skvortsova
    imageUrl: "img/choso.jpg"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    # buttons:
    #   - name: Archives
    #     url: /archives/
    #   - name: Tags
    #     url: /tags/

  homeInfoParams:
    Title: "H3ll0 $tr@ng3r"
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff.

  socialIcons:
    - name: email
      url: "mailto:arinaskvortsovaas@gmail.com"
    - name: telegram
      url: "https://t.me/ar_starling"
    - name: linkedin
      url: "https://www.linkedin.com/in/arstarling/"
    - name: github
      url: "https://github.com/arstarling"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: false  # можно включить позже (например, Giscus)
  hideSummary: false
  hidemeta: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archives     # была опечатка: indentifier → identifier
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40

minify:
  disableXML: false
  minifyOutput: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
